freedesktop compliant: .ctafconf moved to .config/ctafconf

diff --git a/bin/ct-installconf b/bin/ct-installconf
--- a/bin/ct-installconf
+++ b/bin/ct-installconf
@@ -21,7 +21,7 @@
 ## Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 ##
 
-grkdir=~/.ctafconf/etc/grk
+grkdir=~/.config/ctafconf/etc/grk
 
 #catch a signal, else termcaps shit
 _trap_kill ()
@@ -208,36 +208,36 @@ check_app()
 #############################################################################
 ##START
 #############################################################################
-if ! [ -d ~/.ctafconf/ ] ; then
-  echo "Can't find ~/.ctafconf directory"
-  echo "Aborting, verify that you have untar the archive into your home directory"
+if ! [ -d ~/.config/ctafconf/ ] ; then
+  echo "Can't find ~/.config/ctafconf directory"
+  echo "Aborting, you should put the ctafconf folder of your tarball into ~/.config"
   exit
 fi
 
 #install tools
-. ~/.ctafconf/etc/shlib/grktools.sh
+. ~/.config/ctafconf/etc/shlib/grktools.sh
 
 #shellscript frontend
-. ~/.ctafconf/etc/shlib/ssft.sh
+. ~/.config/ctafconf/etc/shlib/ssft.sh
 
 #create default directory
-grk_dir ~/.ctafconf/perso
-grk_dir ~/.ctafconf/perso/semantic
-grk_dir ~/.ctafconf/perso/ssh
-grk_dir ~/.ctafconf/perso/repos
-grk_dir ~/.ctafconf/perso/wallpaper
-grk_dir ~/.ctafconf/perso/bin
-grk_dir ~/.ctafconf/perso/previous
+grk_dir ~/.config/ctafconf/perso
+grk_dir ~/.config/ctafconf/perso/semantic
+grk_dir ~/.config/ctafconf/perso/ssh
+grk_dir ~/.config/ctafconf/perso/repos
+grk_dir ~/.config/ctafconf/perso/wallpaper
+grk_dir ~/.config/ctafconf/perso/bin
+grk_dir ~/.config/ctafconf/perso/previous
 
 #launch profile manager
-. ~/.ctafconf/bin/ct-profile
+. ~/.config/ctafconf/bin/ct-profile
 
-if ! [ -f ~/.ctafconf/perso/user-profile ] ; then
-  echo "Can't find ~/.ctafconf/perso/user-profile directory"
+if ! [ -f ~/.config/ctafconf/perso/user-profile ] ; then
+  echo "Can't find ~/.config/ctafconf/perso/user-profile directory"
   echo "Aborting, execute ct-profile, or relauch install"
   exit
 fi
-. ~/.ctafconf/perso/user-profile
+. ~/.config/ctafconf/perso/user-profile
 
 
 export SSFT_FRONTEND=text
diff --git a/bin/ct-set-bg b/bin/ct-set-bg
--- a/bin/ct-set-bg
+++ b/bin/ct-set-bg
@@ -19,37 +19,37 @@
 ##PORVIDE USER INFO TO ALL CTAFCONF
 ##
 
-if ! [ -f ~/.ctafconf/perso/user-profile ]; then
-  echo "Can't find your ~/.ctafconf/perso/user-profile"
+if ! [ -f ~/.config/ctafconf/perso/user-profile ]; then
+  echo "Can't find your ~/.config/ctafconf/perso/user-profile"
   echo "you should reinstall env with ctafconf-install"
   exit 1
 fi
-. ~/.ctafconf/perso/user-profile
+. ~/.config/ctafconf/perso/user-profile
 
 if [ x$ctafconf_wallpaper = xramdom ] ; then
-  sz=`ls -1 ~/.ctafconf/etc/wallpaper 2>/dev/null | wc -l`
-  sz2=`ls -1 ~/.ctafconf/perso/wallpaper 2>/dev/null | wc -l`
+  sz=`ls -1 ~/.config/ctafconf/etc/wallpaper 2>/dev/null | wc -l`
+  sz2=`ls -1 ~/.config/ctafconf/perso/wallpaper 2>/dev/null | wc -l`
   szall=$(( $sz + $sz2 ))
   pos=$(( `date +%s` % $szall + 1 ))
 
   if [ $pos -gt $sz ]; then
     pos=$(( $pos - $sz ))
-    wallpp=`ls -1 ~/.ctafconf/perso/wallpaper/ | tail -$pos | head -1`
-    wallpp=~/.ctafconf/perso/wallpaper/$wallpp
+    wallpp=`ls -1 ~/.config/ctafconf/perso/wallpaper/ | tail -$pos | head -1`
+    wallpp=~/.config/ctafconf/perso/wallpaper/$wallpp
   else
-    wallpp=`ls -1 ~/.ctafconf/etc/wallpaper/ | tail -$pos | head -1`
-    wallpp=~/.ctafconf/etc/wallpaper/$wallpp
+    wallpp=`ls -1 ~/.config/ctafconf/etc/wallpaper/ | tail -$pos | head -1`
+    wallpp=~/.config/ctafconf/etc/wallpaper/$wallpp
   fi
 
 elif [ x$ctafconf_wallpaper = xramdomperso ]; then
-  sz=`ls -1 ~/.ctafconf/perso/wallpaper 2>/dev/null | wc -l`
+  sz=`ls -1 ~/.config/ctafconf/perso/wallpaper 2>/dev/null | wc -l`
   pos=$(( `date +%s` % $sz + 1 ))
-  wallpp=`ls -1 ~/.ctafconf/perso/wallpaper/ | tail -$pos | head -1`
-  wallpp=~/.ctafconf/perso/wallpaper/$wallpp
+  wallpp=`ls -1 ~/.config/ctafconf/perso/wallpaper/ | tail -$pos | head -1`
+  wallpp=~/.config/ctafconf/perso/wallpaper/$wallpp
 
 else
-  wallpp=~/.ctafconf/etc/wallpaper/$ctafconf_wallpaper
-  wallpp2=~/.ctafconf/perso/wallpaper/$ctafconf_wallpaper
+  wallpp=~/.config/ctafconf/etc/wallpaper/$ctafconf_wallpaper
+  wallpp2=~/.config/ctafconf/perso/wallpaper/$ctafconf_wallpaper
   if [ -f $wallpp2 ]; then
     wallpp=$wallpp2
   fi
